### ISSUE TITLE
Standards

### ISSUE THREAD

**Issue by RobertSimonDB** [Parsifal-M/backstage-opa-backend#9]
Hi, got inspired by this plugin, but still it does not play as I wanted so modifying most of it for our use.

According to [new experimental backend](https://backstage.io/docs/backend-system/architecture/services), there is no need for plugin at all :-D
This would probably qualify as service and that would mean no dependency on API route at all and all can be easily handled by calling it by ref.

If wrapping it as plugin, I would probably just iterate over config items directly and feed it to http-proxy-middleware.
That is the solution used inside the [backstage proxy](https://backstage.io/docs/plugins/proxying/#configuration).
Inspiration could be found for example in [gitlab integration backend](https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/packages/gitlab-backend/src/service/router.ts).
I suggest getting rid of  "policyInput" and just use input directly.

There is no axiom on backstage backend side, node-fetch is the king. [ADR](https://backstage.io/docs/architecture-decisions/adrs-adr013/)

And for my usecase I have more claims generated during user signIn as part of JWT token, so I need to extract it from identity. That means not just using the getIdentity wrapper, but going more deeply and forwarding whole "claims" object from JWT, not just the 1 key rebranded as claims.
So I have little different structure expected on OPA side, maybe that could be considered standard too :-D
But I would expect these could interest many more parties and should be expected, when designing solution which expect OPA to be able to make decisions for all the operations. And custom claims counts there.
Default signIn is same as this, without these grafana OrgIDs and gitlab projectIds lists.
```
const userGroupRefs = await getAllUserGroupRefs(entity);
return ctx.issueToken({
  claims: {
    sub: stringifyEntityRef(entity),
    ent: userGroupRefs,
    grafana: await getAnnotationValues(
      userGroupRefs,
      GRAFANA_ORG_ANNOTATION,
    ),
    gitlab: await getAnnotationValues(
      userGroupRefs,
      GITLAB_PROJECT_ID,
    ),
  },
});
```
Than the forward plugin need to count with and I am going to manually assign "ent" key to claims for conditional decisions to catalog inside OPA. And gitlab/grafana claims to conditional decisions expecting those....

**Comment by Parsifal-M** [comment]
Hello! And welcome!

Thanks a lot for taking the time to provide some feedback and you have made some very good points. I will address them individually here below:

> According to [new experimental backend](https://backstage.io/docs/backend-system/architecture/services), there is no need for plugin at all :-D
This would probably qualify as service and that would mean no dependency on API route at all and all can be easily handled by calling it by ref.

This has been on my mind indeed, I have kept my eye on the progress but not done any deeper reading on it yet so will definitely check on the service route.

> If wrapping it as plugin, I would probably just iterate over config items directly and feed it to http-proxy-middleware.
That is the solution used inside the [backstage proxy](https://backstage.io/docs/plugins/proxying/#configuration).
Inspiration could be found for example in [gitlab integration backend](https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/packages/gitlab-backend/src/service/router.ts).
I suggest getting rid of "policyInput" and just use input directly.

This is quite an interesting approach and I did not consider this 🤔 I need to do a bit of thinking on this one as I can see where you are coming from on here.

> There is no axiom on backstage backend side, node-fetch is the king. [ADR](https://backstage.io/docs/architecture-decisions/adrs-adr013/)

This should be simple enough to do 😄 I have no hard feelings on axios or node-fetch, so I am happy to swap to node-fetch.

> And for my usecase I have more claims generated during user signIn as part of JWT token, so I need to extract it from identity. That means not just using the getIdentity wrapper, but going more deeply and forwarding whole "claims" object from JWT, not just the 1 key rebranded as claims.

I'm quite curious I think I have an idea of your use case but would love to hear more about it, could you give me an example?

Maybe some context from my side, I built this plugin just as a fun "can it be done?" and it serves as a foundation as such for the other two OPA plugins I am playing around with (still kind of WIP) 😅 

- https://github.com/Parsifal-M/backstage-opa-permissions-wrapper
- https://github.com/Parsifal-M/backstage-opa-entity-checker

My idea indeed is that I'd like to have this plugin serve as "the opa backend" plugin i.e. you shouldn't need to make another backend plugin to do something else with OPA (...maybe that's wishful thinking 😅 ) so generalizing it more and more is definitely on the cards, but outside of my own fun little use cases I've not thought of anything else, so this helps a lot!

Thank you!

**Comment by RobertSimonDB** [comment]
Ok, so I finally wired it up in a state I like for my usecase.
Yes, it should probably be in the wrapper repo discussion.
```
export type PolicyClaims = { [claim: string]: unknown };
export type PolicyEvaluationIdentity = {
  user?: string;
  claims?: PolicyClaims;
};

export type PolicyEvaluationInput = {
  permission: {
    name: string;
  };
  identity?: PolicyEvaluationIdentity;
};

export const getPolicydentity = async (
  user?: BackstageIdentityResponse,
): Promise<PolicyEvaluationIdentity> => {
  if (!user) {
    return {};
  }

  const decoded = await decodeJwt(user.token);
  // console.log('##### decoded token: ', decoded);
  const { iss, sub, aud, iat, exp, jti, nbf, ...claims } = decoded;
  return {
    user: user.identity.userEntityRef,
    claims: {
      default: claims.ent,
      ...claims,
    },
  };
};

export const policyEvaluator = (opaClient: OpaClient) => {
  return async (
    request: PolicyQuery,
    user?: BackstageIdentityResponse,
  ): Promise<PolicyDecision> => {
    const identity = await getPolicydentity(user);
    const input: PolicyEvaluationInput = {
      permission: {
        name: request.permission.name,
      },
      identity: identity,
    };

    const response = await opaClient.evaluatePolicy(input);

    if (response.decision.result === 'CONDITIONAL') {
      return {
        result: AuthorizeResult.CONDITIONAL,
        pluginId: response.decision.pluginId,
        resourceType: response.decision.resourceType,
        conditions: response.decision.conditions,
      };
    }

    if (response.decision.result !== 'ALLOW') {
      return { result: AuthorizeResult.DENY };
    }

    return { result: AuthorizeResult.ALLOW };
  };
};
```

**Comment by Parsifal-M** [comment]
Hey! 👋 

> Ok, so I finally wired it up in a state I like for my usecase. Yes, it should probably be in the wrapper repo discussion.
> 
> ```
> export type PolicyClaims = { [claim: string]: unknown };
> export type PolicyEvaluationIdentity = {
>   user?: string;
>   claims?: PolicyClaims;
> };
> 
> export type PolicyEvaluationInput = {
>   permission: {
>     name: string;
>   };
>   identity?: PolicyEvaluationIdentity;
> };
> 
> export const getPolicydentity = async (
>   user?: BackstageIdentityResponse,
> ): Promise<PolicyEvaluationIdentity> => {
>   if (!user) {
>     return {};
>   }
> 
>   const decoded = await decodeJwt(user.token);
>   // console.log('##### decoded token: ', decoded);
>   const { iss, sub, aud, iat, exp, jti, nbf, ...claims } = decoded;
>   return {
>     user: user.identity.userEntityRef,
>     claims: {
>       default: claims.ent,
>       ...claims,
>     },
>   };
> };
> 

I see what you mean now, you want to also be able to send the `token` claims to OPA and not just the `ownershipEntityRefs` that makes sense.

> Regarding API, I would let user decide package-name, not hardcode it in the service plugin.
So it would be 1 endpoint expecting /query/package-name and forwarding it directly.
Or in new way opaService.query(package-name, data)
As OPA have various API and you are using Query for now. I did not dived into the data etc APIs, if you really want to cover whole OPA functionality.
But the forward policy wrapper should be in control which package it wants to interface with, not this forwarder plugin.

Would be nice to cover all the OPA api's but I think for now I just want to get the basics going 😅 but I like this idea will also look into it 😄 

Thanks again!

**Comment by RobertSimonDB** [comment]
Regarding generalizing the API, I have to add another pattern to keep the ruleset manageable.
For example that CONDITIONAL function definition moved to package backstage.permissions.lib, than importing it in my permission packages.
And I have for example backstage.permissions.catalog and separate ones for other app parts/plugins.
So than I really need to manage exact package in my wrapper, for now skipping the backend plugin and fetching directly
```
export class OpaClient {
  private readonly baseUrl: string;
  private readonly logger: Logger;
  private readonly packagePrefix: string;

  constructor(config: Config, logger: Logger) {
    this.baseUrl = config.getString('opaClient.baseUrl');
    // this.package = config.getString('opaClient.policies.rbac.package');
    this.packagePrefix = 'backstage.permissions';
    this.logger = logger;
  }

  async evaluatePolicy(input: PolicyEvaluationInput): Promise<any> {
    // splitting the OPA package name and sanitizing it to match package name enforced rules
    const packageName = input.permission.name.split('.')[0].replace('-', '_');
    const packagePrefixPath = this.packagePrefix.replace('.', '/');
    const requestUrl = `${this.baseUrl}/v1/data/${packagePrefixPath}/${packageName}`;
```
And for example `admin-mode.read` rule name had to be converted into `admin_mode` package name, as `-` is not allowed in OPA.

**Comment by Parsifal-M** [comment]
Hey @RobertSimonDB,

Thanks for all the useful feedback on this, I have made some issues relating to this. Do you mind if I close this for now? Feel free to reach out to me for anything else 😃  and I hope to see you around again!
